### ISSUE TITLE
Error while running package

### ISSUE THREAD

**Issue by Delmark1904** [nestauk/ojd_daps_skills#175]
I have tried to install ojd_daps_skills with the help of pip (as was mentioned in documentation) in Google Colab and tried to install ojd_daps_skills manually, by cloning  full repo and installing all requirements. In all variants - I got next error (maybe someone can help me fix it or identify, what is causing it):
`2023-01-30 16:55:25,125 - SkillsExtractor - INFO - Loading the model from a local location (ner_spacy.py:509)
2023-01-30 16:55:25,126 - SkillsExtractor - INFO - Loading the model from D:\work_main\freysoft\CV_parser\parser_main\skills_taxonomy_ontology\repos\ojd_daps_skills\ojd_daps_skills_data/outputs/models/ner_model/20220825/ (ner_spacy.py:512)
2023-01-30 16:55:25,130 - SkillsExtractor - INFO - Model not found locally - you may need to download it from S3 (set s3_download to True) (ner_spacy.py:518)     
Traceback (most recent call last):
  File "d:/work_main/freysoft/CV_parser/parser_main/skills_taxonomy_ontology/repos/ojd_daps_skills/test.py", line 5, in <module>
    es.load() #load necessary models
  File "d:\work_main\freysoft\CV_parser\parser_main\skills_taxonomy_ontology\repos\ojd_daps_skills\ojd_daps_skills\pipeline\extract_skills\extract_skills.py", line 147, in load
    self.nlp = self.job_ner.load_model(self.ner_model_path, s3_download=self.s3)
  File "d:\work_main\freysoft\CV_parser\parser_main\skills_taxonomy_ontology\repos\ojd_daps_skills\ojd_daps_skills\pipeline\skill_ner\ner_spacy.py", line 521, in 
load_model
    return self.nlp
AttributeError: 'JobNER' object has no attribute 'nlp'`

**Comment by lizgzil** [comment]
Hi @Delmark1904 . Thanks for opening this issue. For now, I can think of two things this might be:
1. Have you installed the spacy model? `python -m spacy download en_core_web_sm`
2. Do you have the aws command line tools installed? https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

I'll have a think about what else it might be if not these! 🤔

**Comment by lizgzil** [comment]
@Delmark1904 may also be worth installing our beta version as pointed out here https://github.com/nestauk/ojd_daps_skills/issues/176

**Comment by Delmark1904** [comment]
> Hi @Delmark1904 . Thanks for opening this issue....

Hi @lizgzil, thanks for replying. Yes, I have installed `en_core_web_sm` and loaded AWS command line tools. I am working on Windows and found, that in setup.py all lines, that contain `open()` should also contain `encoding='UTF-8'`, as far as standard type for Windows is not 'UTF-8' but something else. Also, when I tried loading everything by cloning repo, I needed to unzip "ojd_daps_skills_data.zip" manually and place it to the root directory, that's how I fixed error with ` AttributeError: 'JobNER' object has no attribute 'nlp'`.
After that, I have tried to run example code again and got an error `botocore.exceptions.NoCredentialsError: Unable to locate credentials`, but after re-installing setup.py - this error disappeared, so now everything works :smiley:

**Comment by matteospinazzola** [comment]
Hi @Delmark1904 , I think I've been facing the same issue. Could I ask you for more details on the solution you found? 

What setup.py files did you modify? there aren't in my ojd-daps-skills directory
What was the exact change you made?

Sorry if these are basic questions, but I'm quite new to python.
Thanks for any help!

**Comment by india-kerle** [comment]
@matteospinazzola If you'd like to try and manually download the models from the public s3 bucket, the link to the zipped file containing all relevant models and datasets exist here: `https://open-jobs-indicators.s3.eu-west-1.amazonaws.com/escoe_extension/ojd_daps_skills_data.zip`

You'll need to unzip the file and move it to your relevant path - if you've cloned the repo, it will need to moved to the project’s parent folder - i.e. `ojd_daps_skills/`

**Comment by matteospinazzola** [comment]
thanks @india-kerle ! indeed, it was sufficient to manually download the model and follow your instructions, though with one difference: the unzipped file had to be placed next to `ojd_daps_skills/ ` and not within it.
Now everything works fine. I would definitely recommend this workaround over alternative fixes.

**Comment by yywang40** [comment]
@india-kerle I was pasting the URL to my web browser, but got this error message

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>F7DA4QG7MNJS7A8W</RequestId>
<HostId>Jv0Z2Sgd2hzdik58Km3IOv6bbLxPhf/GhtgI55/5dtUGNFXIFIhOVvZ1NqvaxIVBflfxuxqukqA=</HostId>
</Error>

Any insights on why it's not working for me? Thank you!

**Comment by yywang40** [comment]
I found that the public data file has been updated to a new version. The current link that worked for me is this one:

https://open-jobs-indicators.s3.amazonaws.com/escoe_extension/ojd_daps_skills_data_new.zip
