### ISSUE TITLE
python setup.py egg_info did not run successfully when installing package

### ISSUE THREAD

**Issue by DavidMarguerit** [nestauk/ojd_daps_skills#182]
I am trying to install the package on Windows 10 Pro with Python 3.11, but I get the following error message:

```pip install ojd-daps-skills
Collecting ojd-daps-skills
  Using cached ojd_daps_skills-1.0.1-py3-none-any.whl (60 kB)
Collecting numpy==1.22.4
  Using cached numpy-1.22.4.zip (11.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ojd-daps-skills
  Using cached ojd_daps_skills-1.0.0.tar.gz (5.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\davidm\AppData\Local\Temp\pip-install-2i3_cfyg\ojd-daps-skills_1e86ce5b1e6948448bc7ebe9284edcd0\setup.py", line 19, in <module>
          long_description=open(os.path.join(BASE_DIR, "README.md")).read(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\davidm\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 757: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I upgraded pip, setuptools and wheel since I found on the internet that those packages might be the reason for this error. It did not solve the issue. The versions of these packages are:
pip                      23.0
setuptools          67.3.1
wheel                 0.38.4

Any idea how to solve this issue and install the package?

I also try to install the package using Python 3.10, but I also get an issue, though it is different.

**Comment by lizgzil** [comment]
hello @Daoudooms - thanks so much for trying to use our package. Unfortunately the package has only been developed to work on Macos and Ubuntu. We haven't been able to test it for Windows and as such I imagine there will be several issues (perhaps not just this one). Are you perhaps able to use it on an Ubuntu EC2 instance, or use a [subsystem](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview)?

**Comment by Aiden-RC** [comment]
The specific issue above can be fixed by adding UTF-8 encoding to the open in setup.py

`    long_description=open(os.path.join(BASE_DIR, "README.md"), encoding="utf-8").read(),
`

**Comment by Aiden-RC** [comment]
If you want to make the package work on windows you'll also have to modify the tag_cmd in setup.py to something like this

`
tag_cmd = "git describe --tags --abbrev=0"
tag_cmd = tag_cmd if platform.system() == "Windows" else f"echo $({tag_cmd})"
`

**Comment by lizgzil** [comment]
Thanks for these @Aiden-RC!

**Comment by DavidMarguerit** [comment]
Many thanks @lizgzil and @Aiden-RC, for your answers. I'll try them!
and thank you for the package. It looks very amazing.

**Comment by Aiden-RC** [comment]
> Thanks for these @Aiden-RC!

i have a WIP fork containing windows related changes, 

I can do a Pull Request once i've confirmed the changes indeed work,
The changes are done in a way so it wont affect any other OS

**Comment by lizgzil** [comment]
that would be great @Aiden-RC

**Comment by Aiden-RC** [comment]
> that would be great @Aiden-RC

https://github.com/nestauk/ojd_daps_skills/pull/183
